### ISSUE TITLE
Type definitions for libsodium-wrappers 0.7.4

### ISSUE THREAD

**Issue by jmeinke** [ffflorian/libsodium-type-generator#104] opened 2019-01-23 09:57 UTC
Hello! The type generator does not seem to work perfectly for libsodium-wrappers 0.7.4.

See the following:
![example](https://user-images.githubusercontent.com/941555/51598314-8a751980-1efd-11e9-80f3-a3061d05097d.png)

Everywhere: `string | Uint8Array | undefined` has been replaced by `minsized_buf` in the definitions.

**Comment by ffflorian** [comment] 2019-01-23 10:25
Hi @jmeinke,
the generator was written for version 0.7.3, and not tested for any versions above that. Feel free to create a PR for 0.7.4 :wink:

**Comment by jmeinke** [comment] 2019-01-23 10:48
Hi @ffflorian. I don't have time for it unfortunately.

If the generator only works for 0.7.3 you should probably remove the `-v, --setversion <version>  Set the version for the libsodium.js download (default is 0.7.3)` flag, as it suggests that the generator works for any version of sodium-wrappers.

**Comment by ffflorian** [comment] 2019-01-23 10:53
> you should probably remove the `-v` [...] flag

You are absolutely right. The app was intended to work for future versions but seems like it doesn't work :smiley:

**Comment by ffflorian** [comment] 2019-01-27 11:39
Fixed in [v3.0.0](https://github.com/ffflorian/libsodium-type-generator/releases/tag/v3.0.0)

**Closed by ffflorian** 2019-01-27 11:39 UTC
